### ISSUE TITLE
Change the 'devel' branch to be called 'dev'

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-cloud-install#10]
@sasikeda When I fetched upstream, I noticed a new branch: `devel`.  Is this where we should be pushing code into? 

I do like having a Development branch, but could we call it `dev`

The other projects in scale are all using `dev` branch and it would provide some consistency across the repos.

**Comment by sasikeda** [comment]
Sure, no issues. Done.
