### ISSUE TITLE
README improvements - minimal success path

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-cloud-install#20]
Opening as a follow-up issue for #9, I want to close out #9 quicker, but I think this item would take more time, so creating a 2nd issue to track it.  

> Validate that there's a minimum clear and base success path

Looking at the New/Existing instructions in AWS and Azure, I'd like to be able to launch something minimally.   The instructions says: 

1. cd ibm-spectrum-scale-cloud-install/aws_scale_templates/aws_new_vpc_scale/
2. Create aws_new_vpc_scale_inputs.auto.tfvars.json
3. terraform init/apply... 

So that means the customer is sitting in this repo and HAS to create some custom files.. How does terraform pick it, does it just pick up the various json files in the path? 

If we take that example `aws_new_vpc_scale_inputs.auto.tfvars.json` in the README, as is, could a user launch something into AWS, or would it fail... invalid operator_email? 

If it works, couldn't we ship that example, so if the user wanted to change nothing but had all their credentials already configured, they could just do something like: 

```
git clone <repo> 
cd <some path>
terraform init
terraform apply --auto-approve
```

**Comment by sasikeda** [comment]
Thanks README has been improved.
