### ISSUE TITLE
failure group of nsd's is not set

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-cloud-install#32]
rules for 2AZ Failure  groups
NSD's of all storage servers (nsd servers ) in AZ1 : failure group ID 1
NSD's of all storage servers (nsd servers ) in AZ2:  failure group ID 2
descriptor NSD's : failure group ID 3

rules for 1AZ Failure groups
all NSD's of 50% storage servers in AZ : failure group ID 1
all NSD's of remaining 50% torage servers in AZ : failure group ID 2
descriptor NSD's : failure group ID 3

root@ip-10-0-3-208 ~]# mmlsdisk fs1
disk         driver   sector     failure holds    holds                            storage
name         type       size       group metadata data  status        availability pool
------------ -------- ------ ----------- -------- ----- ------------- ------------ ------------
nsd1         nsd         512          -1 Yes      Yes   ready         up           system
nsd2         nsd         512          -1 Yes      Yes   ready         up           system
desconlynsd  nsd         512          -1 No       No    ready         up           system
[root@ip-10-0-3-208 ~]# uptime
 22:36:25 up  5:41,  1 user,  load average: 0.08, 0.03, 0.05
[root@ip-10-0-3-208 ~]# mmlsmount fs1

File system fs1 is not mounted.
[root@ip-10-0-3-208 ~]# mmdiag
Current GPFS build: "5.0.4.1 ".
Built on Nov 19 2019 at 19:31:28
Running 5 hours 31 minutes 50 secs, pid 18168

Run mmdiag --help for more options
[root@ip-10-0-3-208 ~]# mmlsfs fs1 -A
flag                value                    description
------------------- ------------------------ -----------------------------------
 -A                 no                       Automatic mount option
[root@ip-10-0-3-208 ~]# mmlsfs fs1 -r -R -m -M
flag                value                    description
------------------- ------------------------ -----------------------------------
 -r                 2                        Default number of data replicas
 -R                 2                        Maximum number of data replicas
 -m                 1                        Default number of metadata replicas
 -M                 2                        Maximum number of metadata replicas
[root@ip-10-0-3-208 ~]#

**Comment by rajan-mis** [comment]
I think we have to add this in the cloud  terraform JSON template ,
  ```
"scale_storage":[
    {
      "filesystem": "fs1",
      "blockSize": 4M,
      "defaultDataReplicas": 1,
      "defaultMountPoint": "/mnt/fs1",
      "failureGroup"="**<FailureGroup>**"
```
**<FailureGroup>** == **Identifies the failure group to which the disk belongs. A failure group identifier can be a simple integer or a topology vector consisting of up to three comma-separated integers. The default is -1, which indicates that the disk has no point of failure in common with any other disk.**

**Comment by digvijay2016** [comment]
@rajan-mis : does playbook currently support failureGroup flag ?

**Comment by rajan-mis** [comment]
Yes it supports .

**Comment by rajan-mis** [comment]
Currently playbook support  below mentioned stanza key,


%nsd:
```
  device={{ disk.device }}
  nsd={{ disk.nsd | default(default_nsd) }}
  servers={{ disk.servers }}
  usage={{ disk.usage | default(default_usage) }}
  failureGroup={{ disk.failureGroup | default(-1) }}
  pool={{ disk.pool | default('system') }}
```

**Comment by rajan-mis** [comment]
Sorry failure group needs to be inside disks block,
```
"disks": [
       {
        "device": "/dev/sdd",
        "nsd": "nsd1",
        "servers": "host-vm1",
        "failureGroup" : "**<FailureGroup>**"
       }
```

**Comment by sasikeda** [comment]
I have checked the ansible code, this needs to be added to bridge. no action needed at playbook end.
