### ISSUE TITLE
filesystem automatic mount option should be enabled

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-cloud-install#34]
mmlsfs fs1 -A
flag                value                    description
------------------- ------------------------ -----------------------------------
 -A                 no                       Automatic mount option

**Comment by whowutwut** [comment]
@gandhisanjayv  could you wrap the code output with three backticks, otherwise the markdown formatting will make it look like:

![image](https://user-images.githubusercontent.com/10049070/78855174-2f8bed00-79f1-11ea-8d9d-48860961206b.png)

**Comment by rajan-mis** [comment]
Here also same as issue #32 , we have to add this in the cloud terraform JSON template as part of filesystem attributes , 
`"automaticMountOption": true`

"scale_storage":[
  {
    "filesystem": "fs1",
    "blockSize": 4M,
    "defaultDataReplicas": 1,
    "defaultMountPoint": "/mnt/fs1",
    **"automaticMountOption": true**

**Comment by rajan-mis** [comment]
```
 mmlsmount all
File system fs1 is not mounted.
```
