### ISSUE TITLE
filesystem replica for single AZ is not set correctly

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-cloud-install#35]
Replication factor for metadata should be 2
replication factor for data should be 1
```
[root@ip-10-0-1-96 ~]# mmlsfs fs1 -r -R -m -M
flag                value                    description
------------------- ------------------------ -----------------------------------
 -r                 1                        Default number of data replicas
 -R                 2                        Maximum number of data replicas
 -m                 1                        Default number of metadata replicas
 -M                 2                        Maximum number of metadata replicas
[root@ip-10-0-1-96 ~]#
```

**Comment by rajan-mis** [comment]
I think , we have to add `DefaultMetadataReplicas`  attributes .

**Comment by digvijay2016** [comment]
@rajan-mis :  we did. 

Ansible playbook logs:
`
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): TASK [core/cluster : storage | Consolidate defined filesystem parameters] ******
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): ok: [ip-10-0-1-134.ec2.internal] => (item={'filesystem': 'fs1', 'blockSize': '1M', 'defaultDataReplicas': 1, 'defaultMetaDataReplicas': 2, 'defaultMountPoint': '/gpfs/fs1', 'disks': [{'device': '/dev/xvdf', 'nsd': 'nsd1', 'servers': '10.0.1.134', 'usage': 'dataAndMetadata', 'pool': 'system'}, {'device': '/dev/xvdf', 'nsd': 'nsd2', 'servers': '10.0.1.136', 'usage': 'dataAndMetadata', 'pool': 'system'}, {'device': '/dev/xvdf', 'nsd': 'desconlynsd', 'servers': '10.0.1.94', 'usage': 'descOnly', 'pool': 'system'}]})
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): ok: [ip-10-0-1-134.ec2.internal] => (item={'filesystem': 'fs1', 'blockSize': '1M', 'defaultDataReplicas': 1, 'defaultMetaDataReplicas': 2, 'defaultMountPoint': '/gpfs/fs1', 'disks': [{'device': '/dev/xvdf', 'nsd': 'nsd1', 'servers': '10.0.1.134', 'usage': 'dataAndMetadata', 'pool': 'system'}, {'device': '/dev/xvdf', 'nsd': 'nsd2', 'servers': '10.0.1.136', 'usage': 'dataAndMetadata', 'pool': 'system'}, {'device': '/dev/xvdf', 'nsd': 'desconlynsd', 'servers': '10.0.1.94', 'usage': 'descOnly', 'pool': 'system'}]})
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): ok: [ip-10-0-1-134.ec2.internal] => (item={'filesystem': 'fs1', 'blockSize': '1M', 'defaultDataReplicas': 1, 'defaultMetaDataReplicas': 2, 'defaultMountPoint': '/gpfs/fs1', 'disks': [{'device': '/dev/xvdf', 'nsd': 'nsd1', 'servers': '10.0.1.134', 'usage': 'dataAndMetadata', 'pool': 'system'}, {'device': '/dev/xvdf', 'nsd': 'nsd2', 'servers': '10.0.1.136', 'usage': 'dataAndMetadata', 'pool': 'system'}, {'device': '/dev/xvdf', 'nsd': 'desconlynsd', 'servers': '10.0.1.94', 'usage': 'descOnly', 'pool': 'system'}]})
[0m[0m
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): TASK [core/cluster : storage | Prepare StanzaFile(s) for NSD creation] *********
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): changed: [ip-10-0-1-134.ec2.internal] => (item=fs1)
[0m[0m
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): TASK [core/cluster : storage | Accept server license for NSD servers] **********
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): changed: [ip-10-0-1-134.ec2.internal]
[0m[0m
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): TASK [core/cluster : storage | Create new NSDs] ********************************
[0m[1mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0]: Still creating... [6m50s elapsed][0m[0m
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): changed: [ip-10-0-1-134.ec2.internal] => (item={'diff': [], 'src': '/root/.ansible/tmp/ansible-tmp-1586340864.176635-75365293374405/source', 'changed': True, 'group': 'root', 'uid': 0, 'dest': '/var/tmp/StanzaFile.new.fs1', 'checksum': 'f88be5f30ef13d2d432baae271f63dd64c389fca', 'md5sum': '8cc3cd6d6ddd3bf876523ff4912173f0', 'owner': 'root', 'state': 'file', 'gid': 0, 'secontext': 'unconfined_u:object_r:admin_home_t:s0', 'mode': '0644', 'invocation': {'module_args': {'directory_mode': None, 'force': True, 'remote_src': None, '_original_basename': 'StanzaFile.j2', 'owner': None, 'follow': False, 'local_follow': None, 'group': None, 'unsafe_writes': None, 'setype': None, 'content': None, 'serole': None, 'dest': '/var/tmp/StanzaFile.new.fs1', 'selevel': None, 'regexp': None, 'validate': None, 'src': '/root/.ansible/tmp/ansible-tmp-1586340864.176635-75365293374405/source', 'checksum': 'f88be5f30ef13d2d432baae271f63dd64c389fca', 'seuser': None, 'delimiter': None, 'mode': None, 'attributes': None, 'backup': False}}, 'size': 341, 'failed': False, 'item': 'fs1', 'ansible_loop_var': 'item'})
[0m[0m
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): TASK [core/cluster : storage | Prepare StanzaFile(s) for filesystem creation] ***
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): ok: [ip-10-0-1-134.ec2.internal] => (item=fs1)
[0m[0m
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): TASK [core/cluster : storage | Create new filesystem(s)] ***********************
[0m[1mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0]: Still creating... [7m0s elapsed][0m[0m
[0m[1mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0]: Still creating... [7m10s elapsed][0m[0m
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): changed: [ip-10-0-1-134.ec2.internal] => (item={'diff': {'after': {'path': '/var/tmp/StanzaFile.new.fs1'}, 'before': {'path': '/var/tmp/StanzaFile.new.fs1'}}, 'group': 'root', 'uid': 0, 'changed': False, 'owner': 'root', 'state': 'file', 'gid': 0, 'secontext': 'unconfined_u:object_r:admin_home_t:s0', 'mode': '0644', 'path': '/var/tmp/StanzaFile.new.fs1', 'invocation': {'module_args': {'directory_mode': None, 'force': False, 'remote_src': None, '_original_basename': 'StanzaFile.j2', 'path': '/var/tmp/StanzaFile.new.fs1', 'owner': None, 'follow': False, 'group': None, 'unsafe_writes': None, 'state': 'file', 'content': None, 'serole': None, 'access_time': None, 'setype': None, 'dest': '/var/tmp/StanzaFile.new.fs1', 'selevel': None, 'access_time_format': '%Y%m%d%H%M.%S', 'modification_time': None, 'regexp': None, 'src': None, 'seuser': None, 'recurse': False, '_diff_peek': None, 'delimiter': None, 'mode': None, 'modification_time_format': '%Y%m%d%H%M.%S', 'attributes': None, 'backup': None}}, 'size': 341, 'checksum': 'f88be5f30ef13d2d432baae271f63dd64c389fca', 'dest': '/var/tmp/StanzaFile.new.fs1', 'failed': False, 'item': 'fs1', 'ansible_loop_var': 'item'})
[0m[0m
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): TASK [core/cluster : storage | Mount new filesystem(s)] ************************
[0m[0mmodule.invoke_scale_playbook.null_resource.call_scale_install_playbook[0] (local-exec): skipping: [ip-10-0-1-134.ec2.internal] => (item={'diff': {'after': {'path': '/var/tmp/StanzaFile.new.fs1'}, 'before': {'path': '/var/tmp/StanzaFile.new.fs1'}}, 'group': 'root', 'uid': 0, 'changed': False, 'owner': 'root', 'state': 'file', 'gid': 0, 'secontext': 'unconfined_u:object_r:admin_home_t:s0', 'mode': '0644', 'path': '/var/tmp/StanzaFile.new.fs1', 'invocation': {'module_args': {'directory_mode': None, 'force': False, 'remote_src': None, '_original_basename': 'StanzaFile.j2', 'path': '/var/tmp/StanzaFile.new.fs1', 'owner': None, 'follow': False, 'group': None, 'unsafe_writes': None, 'state': 'file', 'content': None, 'serole': None, 'access_time': None, 'setype': None, 'dest': '/var/tmp/StanzaFile.new.fs1', 'selevel': None, 'access_time_format': '%Y%m%d%H%M.%S', 'modification_time': None, 'regexp': None, 'src': None, 'seuser': None, 'recurse': False, '_diff_peek': None, 'delimiter': None, 'mode': None, 'modification_time_format': '%Y%m%d%H%M.%S', 'attributes': None, 'backup': None}}, 'size': 341, 'checksum': 'f88be5f30ef13d2d432baae271f63dd64c389fca', 'dest': '/var/tmp/StanzaFile.new.fs1', 'failed': False, 'item': 'fs1', 'ansible_loop_var': 'item'})`

**Comment by digvijay2016** [comment]
`[root@ip-10-0-1-134 ~]# mmlsfs fs1 -m
flag                value                    description
------------------- ------------------------ -----------------------------------
 -m                 1                        Default number of metadata replicas
`

**Comment by rajan-mis** [comment]
@digvijay2016  I found there is a typo in the JSON,  it will work once we will correct. 

defaultMeta**d**ataReplicas == This is correct
defaultMeta**D**ataReplicas ==> current Json
