### ISSUE TITLE
Long stack name seems to cause terraform failure

### ISSUE THREAD

**Issue by maroche15** [IBM/ibm-spectrum-scale-cloud-install#41]
Uploaded Single-Az-New-VPC-ECS-FARGATE-SpectrumScale.yaml to AWS CloudFormation and proceeded to create the stack. CloudFormation eventually showed that overall stack creation completed successfully, however server instances are never created. Looking at the logs via CloudWatch, this error is at the top:

```
[31m
[1m[31mError: [0m[0m[1m"name_prefix" cannot be longer than 32 characters, name is limited to 64[0m
[0m  on ../../../resources/aws/compute/iam/iam_role/iam_role.tf line 8, in resource "aws_iam_role" "host_role":
   8: resource "aws_iam_role" "host_role" [4m{[0m
[0m
[0m[0m
[CLOUD-DEPLOY] Waiting for cloudformation stack to obtain create_complete state.
[CLOUD-DEPLOY] Opted deployment for cloud platform:  AWS
[CLOUD-DEPLOY] Collecting IBM Spectrum Scale related infrastructure parameters from Stack:  new-vpc-singleAZ-ecs-fg-test
```

And at the bottom of the logs I see:

```
[CLOUD-DEPLOY] Performing Terraform apply -auto-approve: 
Traceback (most recent call last):
  File "/opt/IBM/ibm-spectrumscale-cloud-deploy/cloud_deploy/cloud_deployer.py", line 36, in <module>
    TerraformUtils.terraform_apply()
  File "cloud_module.py", line 510, in cloud_module.TerraformUtils.terraform_apply
  File "cloud_module.py", line 78, in cloud_module.CommonUtils.local_stream_execution
subprocess.CalledProcessError: Command '['terraform', 'apply', '-auto-approve']' returned non-zero exit status 1.
```

We got to a point where we were thinking it might have been an IAM issue on my end, but then I was able to successfully create a stack using the Multi-AZ template. The thing to note that time  was that I used a much shorter name and that time did not see anything of note in the logs. 

For reference, here are log snippets from one of the successful runs:

```
[CLOUD-DEPLOY] Waiting for cloudformation stack to obtain create_complete state.
[CLOUD-DEPLOY] Opted deployment for cloud platform:  AWS
[CLOUD-DEPLOY] Collecting IBM Spectrum Scale related infrastructure parameters from Stack:  mark-april9
......
[CLOUD-DEPLOY] Performing Terraform apply -auto-approve: 
[0m[1mmodule.invoke_scale_playbook.null_resource.check_tf_data_existence[0]: Creating...[0m[0m
[0m[1mmodule.ansible_vault.null_resource.check_tf_data_existence: Creating...[0m[0m
[0m[1mmodule.invoke_scale_playbook.null_resource.check_tf_data_existence[0]: Provisioning with 'local-exec'...[0m[0m
[0m[1mmodule.ansible_vault.null_resource.check_tf_data_existence: Provisioning with 'local-exec'...[0m[0m
```

cloud stack names that ended up in a failure:
new-vpc-singleAZ-ecs-fargate-test
new-vpc-singleAZ-ecs-fg-test

cloud stack names that resulted ok:
mark-april8
mark-april9

**Comment by sasikeda** [comment]
@maroche15: Thanks for trying out with long stack names.

The stack name with `len("new-vpc-singleAZ-ecs-fg-test") = 28`, which is usually supported by terraform (where higher limit=32). 
But in the current implementation, we are appending stack_name + "Cluster" to role_name_prefix 
```
  role_name_prefix = "${var.stack_name}-Cluster-"
```
So that makes role_name_prefix (28+9 = 37), which hit the higher limit. We could remove "Cluster", but it acts as a differentiation between the scale cluster role vs other roles created by the stack.

**Let us keep the recommendation of stack name lesser than `23` (32-9)**.
