### ISSUE TITLE
Cluster formation fails into existing vpc with template from 4/15

### ISSUE THREAD

**Issue by daved3haan** [IBM/ibm-spectrum-scale-cloud-install#44]
Attempted to use the template https://s3-us-west-2.amazonaws.com/builds-aws1.3/april15/Existing-VPC-ECS-FARGATE-SpectrumScale.yaml in the N. Virginia region to deploy a SS cluster on AWS. 
The existing VPC was created with stack Davetest-0415. The stack I tried to create was named Davetest2-415. In the CloudFormation panel the create finished successfully, but after a period of time there is no cluster created in my EC2 instances.

Logs located at:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/Davetest2-415-ecs_runtask;stream=2020/04/15/%5B$LATEST%5Db2daf73177b54f4588b2ee3ba021fec8

**Comment by daved3haan** [comment]
Forgot to mention, leaving state as is for debug.

**Comment by sasikeda** [comment]
@daved3haan: Thanks for reporting.

In the case of AWS, I would advise the log path (ECSLogGroup) for debugging.
(https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=Davetest2-415-ECSLogGroup;stream=spectrumscale-deploy/spectrumscale-deploy-app/8b6f2180-9415-4e1f-bb99-192d5968fd42;start=2020-04-14T20:26:34Z)

```SpectrumS3Bucket``` parameter is left empty, which resulted in the creation of ```terraform-20200415202631334100000001``` bucket, but this new bucket has been not communicated with backend initialization, which resulted in terraform s3backed configuration failure.

```
Error refreshing state: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, GetObjectInput.Bucket.
```
As a workaround, I suggest to fill the ```SpectrumS3Bucket``` parameter. While we work on adding more validation, checks around it.
