### ISSUE TITLE
Script fails when you set compute_node=0 in the config file.

### ISSUE THREAD

**Issue by sudamsanjay** [IBM/ibm-spectrum-scale-cloud-install#51]
Script fails when you set compute_node=0 in the config file with below error.
Error: Invalid count argument
  on ../../resources/aws/compute/ec2/create.tf line 53, in resource "aws_instance" "main_with_0_data":
  53:   count                   = tonumber(var.total_ebs_volumes) == 0 ? var.total_ec2_count : 0
The given "count" argument value is unsuitable: negative numbers are not supported

**Comment by sasikeda** [comment]
Issue is fixed in commit 54a8d79
