### ISSUE TITLE
Documentation update for terraform deploy steps

### ISSUE THREAD

**Issue by nilbante** [IBM/ibm-spectrum-scale-cloud-install#77]
During terraform deploy, I found there are so many places where documentation needs to update

https://github.com/IBM/ibm-spectrum-scale-cloud-install

1. **Install Ansible and validate:** install ansible link point to yum install steps that installed ansible in /usr/bin/ location. But we need to install in /usr/local/bin/. So this link needs to update to pip install steps

2. Create a keyring file containing the desired passphrase. The keyring file is used by ansible-vaule: I think ansible-value needs to replace by **ansible-vault**

https://github.com/IBM/ibm-spectrum-scale-cloud-install/blob/master/docs/aws.md
3. When we run **terraform init**, we have to enter a bucket value. To enter the bucket value, that should be already created so it will be good if creation steps should be added. 
and default value of key as well.

4. Do we need to add terraform destroy steps as well to cleanup?

**Comment by whowutwut** [comment]
For 

1. if your PATH is set for /usr/bin or /usr/local/bin you don't need to run full path do you? 

2. Yes `vaule` is a typo
