### ISSUE TITLE
aws configure is failing to run on node which created through custom AMI

### ISSUE THREAD

**Issue by nilbante** [IBM/ibm-spectrum-scale-cloud-install#84]
New stack created using custom AMI image and before deleting stack, aws configure ran. But its failing with "command not found"

Below is the current path with the root user

[root@ip-10-0-1-6 tmp]# echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/lpp/mmfs/bin

and aws is available in /usr/local/bin

Its good idea to take care at initial settings or pre-check validation so we will not get such error during aws configure

**Comment by sasikeda** [comment]
Issue fixed.
